name: TicketToRide Continuous Integration

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: src/WordsGeneratorApi
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Checkout Submodule
      uses: actions/checkout@v4
      with:
        repository: Daos16/Uni.Dyslexia.Api
        path: .
        token: ${{ secrets.ACCESS_TOKEN }}
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --configuration Release --no-build