name: TicketToRide Continuous Integration

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: src/WordsGeneratorApi
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: dotnet build --configuration Release
      env:
        DAOS16_NUGET_KEY: ${{ secrets.DAOS16_NUGET_KEY }}
    - name: Test
      run: dotnet test --configuration Release --no-build